const SampleNgo = [
  {
    name: "Shravan seva",
    city: "Vadodara",
    state: "Gujarat",
    area:"Atladara",
    email: "shravansevaofficial@gmail.com",
    contact: "+91-80004 02870",
    website: "https://shravanseva.com",
  },
  {
    name: "Happy Faces",
    city: "Vadodara",
    state: "Gujarat",
    area:"Padra Road",
    email: "info@happyfacesvadodara.com",
    contact: "+91-9925540744",
    website: "https://happyfacesvadodara.com",
  },
  {
    name: "Akshaya patra",
    city: "Vadodara",
    state: "Gujarat",
    area:"Nizampura",
    email: "infodesk@akshayapatra.org",
    contact: "+91-9845671143",
    website: "https://www.akshayapatra.org",
  },
  {
    name: "Baroda Citizens Council",
    city: "Vadodara",
    state: "Gujarat",
    area: "Manjalpur",
    email: "admin@barodacitizenscouncil.org",
    contact: "+91-7990576688",
    website: "https://barodacitizenscouncil.org",
  },
  {
    name: "VNM Foundation",
    city: "Vadodara",
    state: "Gujarat",
    area: "Alkapuri",
    email: "vnmfoundation2018@gmail.com",
    contact: "+91-8734872606",
    website: "https://www.vnmfoundation.com",
  },
  {
    name: "Prathibha Foundation",
    city: "Vadodara",
    state: "Gujarat",
    area: "Old Chhani Road",
    email: "foundation.pratibha@gmail.com",
    contact: "+91-9426233488",
    website: "https://pratibhafoundation.org",
  },
  {
    name: "Faith Foundation",
    city: "Vadodara",
    state: "Gujarat",
    area: "Nizampura",
    email: "info@faithfoundationindia.org",
    contact: "+91-9173671228",
    website: "https://faithfoundationindia.org",
  },
  {
    name: "SEWA",
    city: "Ahmedabad",
    state: "Gujarat",
    area: "Nizampura",
    email: "contact@sewa.org",
    contact: "-9876098674",
    website: "https://www.sewa.org",
  },
  {
    name: "GiveIndia",
    city: "Mumbai",
    state: "Maharashtra",
    area: "Nizampura",
    email: "support@giveindia.org",
    contact: "-9876543120",
    website: "https://www.giveindia.org",
  },
  {
    name: "Deepalaya",
    city: "New Delhi",
    state: "Delhi",
    area: "Nizampura",
    email: "info@deepalaya.org",
    contact: "-9876523321",
    website: "https://www.deepalaya.org",
  },
]

module.exports = { data : SampleNgo};
