const foodName = require("../src/models/food_name");

const indianFoods = [
    { name: "Rice", keywords: ["grains", "staple", "boiled", "Indian cuisine"] },
    { name: "Roti", keywords: ["flatbread", "wheat", "Indian bread", "chapati"] },
    { name: "Sabji", keywords: ["vegetables", "curry", "spiced", "side dish"] },
    { name: "Dal", keywords: ["lentils", "protein", "stew", "comfort food"] },
    { name: "Chole", keywords: ["chickpeas", "curry", "spicy", "Punjabi"] },
    { name: "Rajma", keywords: ["kidney beans", "curry", "protein-rich", "North Indian"] },
    { name: "Paneer Tikka", keywords: ["cottage cheese", "grilled", "spicy", "tandoor"] },
    { name: "Butter Chicken", keywords: ["chicken", "creamy", "tomato-based", "Punjabi"] },
    { name: "Biryani", keywords: ["rice", "spiced", "fragrant", "Hyderabadi"] },
    { name: "Dosa", keywords: ["fermented", "South Indian", "crispy", "rice batter"] },
    { name: "Idli", keywords: ["steamed", "fermented", "South Indian", "breakfast"] },
    { name: "Sambar", keywords: ["lentil soup", "tamarind", "spiced", "South Indian"] },
    { name: "Vada", keywords: ["fried", "lentil", "savory", "South Indian snack"] },
    { name: "Pav Bhaji", keywords: ["bread", "spiced mash", "street food", "Mumbai"] },
    { name: "Pani Puri", keywords: ["crispy", "spicy water", "street food", "chaat"] },
    { name: "Aloo Paratha", keywords: ["stuffed bread", "potato", "Punjabi", "breakfast"] },
    { name: "Malai Kofta", keywords: ["dumplings", "creamy", "North Indian", "gravy"] },
    { name: "Dhokla", keywords: ["steamed", "fermented", "Gujarati", "snack"] },
    { name: "Poha", keywords: ["flattened rice", "light", "Maharashtrian", "breakfast"] },
    { name: "Upma", keywords: ["semolina", "savory", "South Indian", "breakfast"] },
    { name: "Kadhi", keywords: ["yogurt-based", "gram flour", "spiced", "North Indian"] },
    { name: "Bhindi Masala", keywords: ["okra", "stir-fry", "spiced", "vegetarian"] },
    { name: "Baingan Bharta", keywords: ["eggplant", "roasted", "spiced", "North Indian"] },
    { name: "Palak Paneer", keywords: ["spinach", "cottage cheese", "North Indian", "gravy"] },
    { name: "Matar Paneer", keywords: ["peas", "cottage cheese", "North Indian", "gravy"] },
    { name: "Gajar Ka Halwa", keywords: ["carrot", "sweet", "dessert", "North Indian"] },
    { name: "Rasgulla", keywords: ["sweet", "spongy", "Bengali", "dessert"] },
    { name: "Gulab Jamun", keywords: ["milk-based", "fried", "sweet", "dessert"] },
    { name: "Jalebi", keywords: ["crispy", "syrupy", "sweet", "dessert"] },
    { name: "Lassi", keywords: ["yogurt", "cooling", "sweet or salty", "Punjabi"] },
    { name: "Masala Chai", keywords: ["tea", "spiced", "milk-based", "Indian beverage"] },
    { name: "Misal Pav", keywords: ["spicy", "Maharashtrian", "sprouts curry", "street food"] },
    { name: "Kachori", keywords: ["fried", "stuffed", "savory snack", "Rajasthani"] },
    { name: "Samosa", keywords: ["fried", "stuffed", "potato-filled", "street food"] },
    { name: "Kheer", keywords: ["rice pudding", "milk-based", "sweet", "dessert"] },
    { name: "Dal Baati Churma", keywords: ["lentils", "baked wheat balls", "Rajasthani", "meal"] },
    { name: "Thepla", keywords: ["flatbread", "spiced", "Gujarati", "breakfast"] },
    { name: "Handvo", keywords: ["savory cake", "lentil-based", "Gujarati", "snack"] },
    { name: "Pesarattu", keywords: ["green gram", "crispy", "South Indian", "breakfast"] },
    { name: "Appam", keywords: ["rice pancake", "fermented", "South Indian", "soft"] },
    { name: "Chettinad Chicken", keywords: ["spicy", "South Indian", "chicken", "flavorful"] },
    { name: "Hyderabadi Biryani", keywords: ["fragrant", "spiced", "rice", "Hyderabad specialty"] },
    { name: "Bhature", keywords: ["deep-fried", "fluffy", "North Indian", "bread"] },
    { name: "Modak", keywords: ["sweet", "steamed or fried", "Maharashtrian", "Ganesh festival"] },
    { name: "Sev Puri", keywords: ["chaat", "crispy", "street food", "spicy"] },
    { name: "Dabeli", keywords: ["spiced potato", "street food", "Gujarati", "sweet & tangy"] },
    { name: "Sarson Da Saag", keywords: ["mustard greens", "Punjabi", "spiced", "winter dish"] },
    { name: "Makki Di Roti", keywords: ["cornmeal bread", "Punjabi", "flatbread", "winter special"] },
    { name: "Chakli", keywords: ["crispy", "spiral snack", "savory", "Diwali special"] },
    { name: "Pongal", keywords: ["rice", "lentils", "Tamil Nadu", "comfort food"] },
    { name: "Bisi Bele Bath", keywords: ["spiced", "rice", "Karnataka", "lentil-based"] },
    { name: "Chicken 65", keywords: ["fried", "spicy", "South Indian", "starter"] },
    { name: "Mysore Pak", keywords: ["sweet", "ghee", "gram flour", "South Indian"] },
    { name: "Naan", keywords: ["flatbread", "tandoor", "North Indian", "soft"] },
    { name: "Bhakarwadi", keywords: ["spicy", "crispy", "Maharashtrian", "snack"] },
    { name: "Neer Dosa", keywords: ["thin dosa", "coconut", "South Indian", "light"] },
    { name: "Shahi Paneer", keywords: ["cottage cheese", "creamy", "North Indian", "royal dish"] },
    { name: "Bombay Sandwich", keywords: ["vegetables", "grilled", "street food", "Mumbai"] }
];

module.exports = { foodName : indianFoods};

